# Generated by Django 3.2.9 on 2021-11-15 21:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('borrower_name', models.CharField(blank=True, max_length=100)),
                ('borrower_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_name', models.CharField(blank=True, max_length=100)),
                ('investor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan_period', models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 14, 21, 11, 3, 15347))),
                ('loan_status', models.CharField(choices=[('Requested', 'Requested'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Requested', max_length=100)),
                ('annual_interest_rate', models.FloatField(default=0.15)),
                ('lenme_fee', models.FloatField(default=3.0)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.borrower')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.investor')),
            ],
        ),
    ]
