# Generated by Django 3.2.9 on 2021-11-16 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 15, 6, 2, 17, 665676)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Offered', 'Offered'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Requested', max_length=100),
        ),
    ]
