# Generated by Django 3.2.9 on 2021-11-16 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211116_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_period',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 5, 15, 10, 47, 23, 15276)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Offered', 'Offered'), ('Funded', 'Funded'), ('Paid', 'Paid'), ('Completed', 'Completed')], default='Requested', max_length=100),
        ),
    ]
